image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
    - npm install jest kohanajs @kohanajs/mod-database-adapter-better-sqlite3
  artifacts:
    paths:
      - node_modules/

testing_testing:
  stage: test
  script: npm test